---
users:

  'plone':
    name: 'Plone installation'
    email: 'marketing@plone.org'
    public_keys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINQCYLO56pcTTKp1GziM6lVbuV9YYsy+qVS3rXUAA+6k jk@kleinundpartner.at"
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
